/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

const max = 4000000;

let sum = 2;
let pOne = 2;
let pTwo = 1;
let c = 3;

while (c < max) {
    if (c % 2 == 0) {
        sum += c;
    }
    pTwo = pOne;
    pOne = c;
    c = pOne+pTwo;
}

output("Total; " + sum);